version: "3.2"
services:

  mongodb:
    image: mongo:4
    networks:
      - superdesk
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis:
    image: redis:3
    networks:
      - superdesk
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - discovery.type=single-node
    networks:
      - superdesk
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
  
  superdesk-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - superdesk

  superdesk-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - superdesk

networks:
    superdesk:
        driver: bridge

volumes:
  mongo:
  elastic:
