name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - test-ci-cd

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with SSM 
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: ~
          command: git clone https://github.com/canadianpress/superdesk-cp-2.git
          command: cd superdesk-cp-2
          command: git fetch origin test-ci-cd
          command: git switch test-ci-cd