name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - test-ci-cd

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd ~
            git clone git@github.com:canadianpress/superdesk-cp-2.git
            cd superdesk-cp-2
            git fetch origin test-ci-cd
            git switch test-ci-cd